objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quick_Text__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Quick Texts</relationshipLabel>
        <relationshipName>Quick_Texts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Quick Texts</relationshipLabel>
        <relationshipName>Quick_Texts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quick_Text_Category__c</fullName>
        <label>Quick Text Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                    <default>true</default>
                    <label>Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quick_Text_Message__c</fullName>
        <label>Quick Text Message</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Quick Text</label>
    <nameField>
        <label>Quick Text Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quick Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuickTextSelectorControllerTest.cls
@isTest 
private class QuickTextSelectorControllerTest {

	@isTest
	private static void testGetQuickText() {
        Brand__c testBrand = new Brand__c(Name='TestBrand');
        insert testBrand;
        Language__c testLanguage = new Language__c(Name='TestBrand');
        insert testLanguage;
        Quick_Text__c testQuickText = new Quick_Text__c(
            Name = 'TEST',
            Brand__c = testBrand.Id,
            Language__c = testLanguage.Id,
            Quick_Text_Message__c = 'HELLO',
            Quick_Text_Category__c = 'Email');
        insert testQuickText;    

        Contact testContact = new Contact(
            LastName = 'TEST',
            Brand__c = testBrand.Id,
            Language__c = testLanguage.Id);
        insert testContact;

        Test.startTest();
            List<Quick_Text__c> quickTestArray = QuickTextSelectorController.getQuickText(testContact.Id);
            String actualValue = quickTestArray.get(0).Quick_Text_Message__c;
        Test.stopTest();

        System.assertEquals('HELLO', actualValue);
	}
}