objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quick_Text__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Quick Texts</relationshipLabel>
        <relationshipName>Quick_Texts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Quick Texts</relationshipLabel>
        <relationshipName>Quick_Texts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quick_Text_Category__c</fullName>
        <label>Quick Text Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                    <default>true</default>
                    <label>Email</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quick_Text_Message__c</fullName>
        <label>Quick Text Message</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Quick Text</label>
    <nameField>
        <label>Quick Text Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quick Texts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuickTextSelectorController.cls
public class QuickTextSelectorController  {
    
    @AuraEnabled
    public static Quick_Text__c[] getQuickText(Id contactIdVal) {
        try {
            Contact currentContact = [SELECT Id, Name, Brand__c, Language__c FROM Contact WHERE Id =: contactIdVal];

            if (String.isBlank(currentContact.Brand__c)){
                return null;
            }

            List<Quick_Text__c> result;

            if (!String.isBlank(currentContact.Language__c)) {
                result = [
                  SELECT Name, Quick_Text_Message__c, Quick_Text_Category__c, Brand__c, Language__c 
                  FROM Quick_Text__c 
                  WHERE Quick_Text_Category__c = 'Email' 
                      AND Brand__c =: currentContact.Brand__c 
                      AND Language__c =: currentContact.Language__c
                ];
            } else {
                result = [
                  SELECT Name, Quick_Text_Message__c, Quick_Text_Category__c, Brand__c, Language__c 
                  FROM Quick_Text__c 
                  WHERE Quick_Text_Category__c = 'Email' 
                      AND Brand__c =: currentContact.Brand__c
                ];
            }


            return result;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getTypeName() + ': ' + ex.getMessage());
        }
    }
}