objects/Email_Message__c.object
<CustomObject>
    <fields>
        <fullName>Base_Parent_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Base Parent ID</label>
        <referenceTo>Email_Message__c</referenceTo>
        <relationshipLabel>Email Messages (Base Parent ID)</relationshipLabel>
        <relationshipName>Email_Messages1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Cc_Address__c</fullName>
        <label>Cc Address</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Date__c</fullName>
        <label>Email Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From_Address__c</fullName>
        <label>From Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Immediate_Parent_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Immediate Parent ID</label>
        <referenceTo>Email_Message__c</referenceTo>
        <relationshipLabel>Email Messages (Immediate Parent ID)</relationshipLabel>
        <relationshipName>Email_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Email Messages</relationshipLabel>
        <relationshipName>Email_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Address__c</fullName>
        <label>To Address</label>
        <type>TextArea</type>
    </fields>
    <label>Email Message</label>
    <nameField>
        <displayFormat>EM-{00000}</displayFormat>
        <label>Email Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseEmailHandler.cls
global class CaseEmailHandler implements Messaging.InboundEmailHandler {
 
  global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email, 
                                                       Messaging.InboundEnvelope env){
 
    // Create an InboundEmailResult object for returning the result of the 
    // Apex Email Service
    Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
    
    string splitIdFromsubject = email.subject.substringAfter('ID:');
    String ImmediateParentId =  splitIdFromsubject.substringBefore(']');                                                      
    system.debug('subject ----->'+splitIdFromsubject);   
     
    Email_Message__c EmailMessageId = new Email_Message__c();
    EmailMessageId = [Select Id,name,Base_Parent_ID__c,Parent_Case__c from Email_Message__c where id =: ImmediateParentId.trim() limit 1];                                                       
    List<Email_Message__c> EmailMessageList = new List<Email_Message__c>();
    List<Attachment> AttachmentList = new List<Attachment>();                                                       
    
    Email_Message__c EmailMessageObject = new Email_Message__c();
    EmailMessageObject.Cc_Address__c = string.valueof(email.ccAddresses);
    EmailMessageObject.Body__c = email.htmlBody;
    EmailMessageObject.Email_Date__c = system.today();
    EmailMessageObject.From_Address__c = email.fromAddress;
    EmailMessageObject.Immediate_Parent_ID__c = ImmediateParentId.trim();
    EmailMessageObject.Parent_Case__c =   EmailMessageId.Parent_Case__c;                                                     
    EmailMessageObject.Base_Parent_ID__c = EmailMessageId.Base_Parent_ID__c == null ? ImmediateParentId.trim() :  EmailMessageId.Base_Parent_ID__c;                                       
    EmailMessageObject.Subject__c = email.subject;
    EmailMessageObject.To_Address__c = string.valueof(email.toAddresses); 
    
    EmailMessageList.add(EmailMessageObject);     

    if(!EmailMessageList.isEmpty())
    {
            insert EmailMessageList;
       }                                              
      
    
    if(email.textAttachments != null)
        {
            // Save attachments, if any
            for (Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
              Attachment attachment = new Attachment();
             
              attachment.Name = tAttachment.fileName;
              attachment.Body = Blob.valueOf(tAttachment.body);
              attachment.ParentId = EmailMessageList[0].Id;
              AttachmentList.add(attachment);
            }
        }
                                                           
        if(email.binaryAttachments != null)
        {
            for (Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
              Attachment attachment = new Attachment();
             
              attachment.Name = bAttachment.fileName;
              attachment.Body = bAttachment.body;
              attachment.ParentId = EmailMessageList[0].Id;
              AttachmentList.add(attachment);
            }
        }
       if(!AttachmentList.isEmpty())
    	{
            insert AttachmentList;
        }
        
                                                             
   // Return the result for the Apex Email Service
   return result;
  }
}